[package]
name = "figdriver"
  version = "0.2.0"
authors = ["Claudio Matsuoka <cmatsuoka@gmail.com>"]
edition = "2021"

[lib]
name = "figdriver"
path = "src/lib.rs"

[[bin]]
name = "figlet"
path = "src/bin/figlet/main.rs"
doc = false

[dependencies]
pico-args = { version = "0.5", features = ["combined-flags", "short-space-opt", "eq-separator"] }

[profile.release]
lto = true
